/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/portfolioTheme.ts
 * Command: astryx theme build src/theme/portfolioTheme.ts --out src/theme/portfolio.css
 * CLI: @astryxdesign/cli@0.6.4
 * Core: @astryxdesign/core@0.6.4
 */

import type {DefinedTheme} from '@astryxdesign/core/theme';
export declare const portfolioTheme: DefinedTheme;
